### PR TITLE
Add build file for Travis-CI

### PR DESCRIPTION
**Pull request by ghewgill**
Travis-CI provides a free continuous integration service for Github projects. The [Travis CI Getting Started](http://docs.travis-ci.com/user/getting-started/) page describes the steps necessary to set this up. The `.travis.yml` file in this pull request currently works, but may need modification in the future if the example `Makefile` changes. You can see the current results for my fork at https://travis-ci.org/ghewgill/minijson_writer.

### CODE REVIEW

**Comment by giacomodrago** [comment]
My `Makefile` is very, *very* broken. Before doing this, let me replace it with something which is based on `cmake` or `autotools`.

**Comment by ghewgill** [comment]
Sure, no worries. Let me know (comment here I guess) when you've got something that is not so broken, and I can adjust the travis build to match.

**Comment by giacomodrago** [comment]
I have added a supposedly (I have some doubts) portable `CMakeLists.txt` file. It would be of great help if you tested it in your environment, and then, if you fancy it, on Travis-CI as well.

Ideally, one should build and test both in C++03 and in C++11 modes, as the library claims to support both and there scary `#ifdef`s here and there to make this happen. You can build in C++11 mode by passing an extra parameter to `cmake` (you find it in a comment inside `CMakeLists.txt` itself).

With C++03 you need Boost, and I should probably enforce this in `CMakeLists.txt` when I discover how to do it.

I thank you in advance. :+1:

**Comment by giacomodrago** [comment]
I tried to write a Travis CI configuration file myself. It should build with different versions of gcc and clang, both in C++03 and C++11 mode.

**Comment by ghewgill** [comment]
Looks good. The `CMakeLists.txt` file works fine for me on Mac OS X. I'll try on Windows when I get a chance, might be a couple more days.

It might be worth including in the readme a note about how to download and set up GTest locally (following the advice in the [GTest FAQ](https://github.com/google/googletest/blob/master/googletest/docs/FAQ.md#why-is-it-not-recommended-to-install-a-pre-compiled-copy-of-google-test-for-example-into-usrlocal) about not installing it globally).

**Comment by giacomodrago** [comment]
Good idea.

**Comment by ghewgill** [comment]
The `cmake` build seems to work on Windows too. The only extra thing I had to do is build the GTest makefiles with `cmake -G "NMake Makefiles" -D gtest_force_shared_crt=ON .` because the default GTest build (static CRT) is incompatible with the default dynamically linked CRT (no idea why GTest chose that default option).

**Comment by giacomodrago** [comment]
Yes, same here. Every time I deal with libraries on Windows environments I have to go through this perennial nightmare of mismatching runtimes.

**Pull request closed without merging**
