### PR TITLE
Add pretty-printing support

### PR DESCRIPTION
**Pull request by ghewgill**

### CODE REVIEW

**Comment by ghewgill** [comment]
Good point, I hadn't considered the `default_value_writer` case. I'll see what I can think of too.

I was also considering that it would be nice to be able to supply an indent width (instead of just `true`), or even a string to use for each indent level (to support tabs).

**Comment by ghewgill** [comment]
Updated to support arbitrary indent levels (spaces) or tabs.

**Comment by giacomodrago** [comment]
That's great. If you can handle `default_value_writer::operator()` by detecting a three-args overload you'd probably save me 30 mins of template headache.

**Comment by ghewgill** [comment]
I'm afraid my C++-fu is insufficient to make this work. My non-compiling attempt is in https://github.com/ghewgill/minijson_writer/commit/037f27d9ac8c8212f286e95521b14aa9f925a7a2 if that helps any.

I had completely different idea for pretty-printing, that would introduce an iomanipulator, or a trait, or a facet, or something that would wrap around an ostream and provide JSON-specific pretty printing support. The user might use it as:

    minijson::object_writer writer(minijson::pretty_print_ostream(stream));

or

    stream << minijson::pretty_print;
    minijson::object_writer writer(stream);

but I don't know enough about how the iostream system works to do that, either. I tried but it was far from obvious.

**Comment by giacomodrago** [comment]
I've prototyped something similar to what you've tried, but it is C++03 compatible. I'll merge the other branches, and finally fix this prettyprinting thing once for all :)
Thanks for you input :+1:

**Comment by giacomodrago** [comment]
I drafted the template machinery here: https://github.com/giacomodrago/minijson_writer/commit/05a7f62bf7b1ab9ad7b4000d80b8abdb2751657f. The idea I have sketched is to have a `writer_configuration` object (as opposed to an ad-hoc parameter for pretty-printing only, as this allows for future extension instead) which is copied into the writers that write nested objects. That `writer_configuration` object shall contain a hidden `depth` field and carry the pretty-printing settings of course.

**Comment by giacomodrago** [comment]
I have added experimental pretty-printing support here: https://github.com/giacomodrago/minijson_writer/commit/365d9772203a0734056c3877ce51f7d9d35641c7

I'd love to receive your feedback! :+1:

**Comment by ghewgill** [comment]
Looks great. Using a `writer_configuration` is a good idea. It's unfortunate that any existing custom writers will need changes to work with pretty printing, but at least the required changes are straightforward (and shouldn't require any additional changes for future writer features).

Only suggestion is to write the indent using a single string, see inline comment.

**Comment by giacomodrago** [comment]
I wish I had that idea before. The necessity of "almost" (because old code will compile and work as expected) breaking the interface of custom writers is a shame, and it's the proof that I did a mistake with the original design.

**Comment by giacomodrago** [comment]
Hi, I finalised pretty-printing. Before merging it into `master`, it would be great if you had a look at it, and told me if it works for you, the documentation is understandable, and the whole thing compiles without warnings in your environment.

I am sorry I didn't merge your pull request, but as you realised, there were bigger design problems to patch, and pretty-printing was just the tip of the iceberg.

**Comment by ghewgill** [comment]
Yes, looks good from here. I've so far only tried it with `clang` on OS X, but I don't see any obvious issues. Thanks!

**Comment by giacomodrago** [comment]
Great, merging now.

**Pull request closed without merging**
