### PR TITLE
Include <stdexcept> in test suite for std::runtime_error

### PR DESCRIPTION
**Pull request by ghewgill**

### CODE REVIEW

**Comment by giacomodrago** [comment]
What needs it? Under what compiler it fails to build because of that?

**Comment by ghewgill** [comment]
The backstory is that I'm trying to set up an automatic test build for Travis-CI (but it's not quite working yet). One of the compilers there complained about the use of `std::runtime_error` (sorry, I don't recall which one). I looked up http://en.cppreference.com/w/cpp/error/runtime_error and the required header file is `<stdexcept>`. That fixed the problem on Travis-CI, and seemed like a safe, appropriate change to make.

**Comment by giacomodrago** [comment]
If you find out which compiler, I am more than happy to merge. But so far it's too vague for me :)

**Comment by ghewgill** [comment]
In cases like this, my usual approach is to follow the documentation for which header should be included, rather than relying on finding a counterexample on a particular platform/compiler combination. 

In any case, the compiler with the problem appeared to be g++ 4.8. You can see the output from the Travis-CI build here: https://travis-ci.org/ghewgill/minijson_writer/jobs/78293432 although I'm not sure how long that link will remain available.

**Comment by giacomodrago** [comment]
Same approach here -- the problem is that I simply forgot I was catching a `std::runtime_error` on line 388, which is a recent addition by the way. You could have told me: "you catch `std::runtime_error` and you forgot to add the appropriate header". Travis-Cl, and any backstory for that matter, is distracting in this case.

**Comment by ghewgill** [comment]
Ah, got it. I should have explained more about the change in the description. Thanks.

**Comment by giacomodrago** [comment]
Well actually I should have searched in the source code but was busy doing something else. Next time, please shout pointing at the very offending line! :+1:

**Pull request merged**
